generos_dict = {
    'acao': 'Ação',
    'action-adventure': 'Action & Adventure',
    'animacao': 'Animação',
    'aventura': 'Aventura',
    'cinema-tv': 'Cinema TV',
    'comedia': 'Comédia',
    'crime': 'Crime',
    'drama': 'Drama',
    'familia': 'Família',
    'fantasia': 'Fantasia',
    'faroeste': 'Faroeste',
    'ficcao-cientifica': 'Ficção científica',
    'guerra': 'Guerra',
    'historia': 'História',
    'misterio': 'Mistério',
    'musica': 'Música',
    'reality': 'Reality',
    'romance': 'Romance',
    'sci-fi-fantasy': 'Sci-Fi & Fantasy',
    'soap': 'Soap',
    'terror': 'Terror',
    'thriller': 'Thriller',
    'war-politics': 'War & Politics'
}