generos_dict = [
    "Ação",
    "Action & Adventure",
    "Animação",
    "Aventura",
    "Cinema TV",
    "Comédia",
    "Crime",
    "Drama",
    "Família",
    "Fantasia",
    "Faroeste",
    "Ficção científica",
    "Guerra",
    "História",
    "Mistério",
    "Música",
    "Reality",
    "Romance",
    "Sci-Fi & Fantasy",
    "Soap",
    "Terror",
    "Thriller",
    "War & Politics"
]